name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronized

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: | 
          sudo apt-get update -qq
          sudo apt-get install gcc-multilib
          sudo apt-get install -y --no-install-recommends \
            libglfw3 libglfw3-dev libx11-dev libxcursor-dev \
            libxrandr-dev libxinerama-dev libxi-dev libxext-dev \
            libxfixes-dev libwayland-dev libxkbcommon-dev
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure
        run: |
          autoreconf -vi
          ./configure --enable-tests
      - name: Build
        run: make
      - name: Tests
        run: make check
