name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronized

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure
        run: |
          autoreconf -vi
          ./configure --enable-tests
      - name: Build
        run: make
      - name: Tests
        run: make check
